version: '3.9'
services:
  backend:
    build: ./backend
    container_name: marktrade-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./ai_models:/app/ai_models
  frontend:
    image: node:20
    container_name: marktrade-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000/api
